services:
  avd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avd
    restart: unless-stopped
    environment:
      AVD_PROXY: ${AVD_PROXY:-}
      MAX_RETAINED_VIDEOS: ${MAX_RETAINED_VIDEOS:-0}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
